# This workflow builds a Java project using Gradle and caches dependencies to optimize build times.
# It is compatible with projects developed in IntelliJ IDEA.

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    # Set up JDK 17 (the version you used in IntelliJ IDEA)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Set up Gradle (use Gradle wrapper if available)
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0

    # Run Gradle build using Gradle Wrapper (./gradlew)
    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generate and submit dependency graph for Dependabot Alerts
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4.0.0
