# This workflow builds a Java project using Gradle and caches dependencies to optimize build times.
# It is compatible with projects developed in IntelliJ IDEA.

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    # Set up JDK 17 (the version you used in IntelliJ IDEA)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Set up Gradle with a specific version if Gradle wrapper is not present
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0
      with:
        gradle-version: '8.9'  # Specify your desired version of Gradle here

    # Run Gradle build
    - name: Build with Gradle
      run: gradle build
